spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ov23li1HmimBR36lA7Zk
            client-secret: 1de61467c577f6f8c8e1cc5a2aff68ee9de65d85
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

jwt:
  secret-key: 1234567890123456789012345678901234567890
  expiration-ms: 3600000
